---

- name: check if runit is installed
  yum:
    list: runit
  register: runit_installed

# - name: Download zsh installer
#     get_url: url=https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh dest=/tmp/zsh-installer.sh
#
#   - name: Execute the zsh-installer.sh
#     script: /tmp/zsh-installer.sh

- name: add yum repo for runit if it doesn't exist
  shell: "curl -s https://packagecloud.io/install/repositories/imeyer/runit/script.rpm.sh | sudo bash"
  when: (runit_installed.results|length == 0)

- name: centos - install package runit
  yum:
    name: runit
    state: present
    update_cache: yes

- name: centos - start and enable runit service
  service:
    name: runsvdir-start
    enabled: yes
    state: started
  when: ansible_distribution_major_version == "7"

- name: dependencies
  yum:
    name: libselinux-python
    state: present
