---

- name: install runit on Debian
  include_tasks: install_debian.yml
  when: ansible_os_family == "Debian"

- name: install runit on CentOS
  include_tasks: install_centos.yml
  when: ansible_os_family == "RedHat"
