---

- include_tasks: java.yml
  when: es_java_install
  tags:
      - java

- name: create elasticsearch group
  group:
    name={{ es_group }}
    state=present

- name: create elasticsearch user
  user:
    name={{ es_user }}
    group={{ es_group }}

- name: create elasticsearch directories
  file:
    state=directory
    path={{ item }}
    owner={{ es_user }}
    group={{ es_group }}
    recurse=true
  with_items:
    - "{{ es_install_dir }}"
    - "{{ es_log_dir }}"
    - "{{ es_build_folder }}"

- name: download elasticsearch archive
  get_url:
    url={{ es_url }}
    dest={{ es_build_folder }}/{{ es_archive }}
  register: es_was_downloaded

- name: copy and unpack elasticsearch archive
  unarchive:
    src={{ es_build_folder }}/{{ es_archive }}
    dest={{ es_install_dir }}
    copy=no

- name: link installed elasticsearch directory to current
  file:
    state=link
    src={{ es_install_dir }}/{{ es_archive|replace('.tar.gz', '') }}
    path={{ es_install_dir }}/current
    owner={{ es_user }}
    group={{ es_group }}

- name: provide access permission to elasticsearch directory
  file:
    state=directory
    path={{ es_install_dir }}/{{ es_archive|replace('.tar.gz', '') }}
    owner={{ es_user }}
    group={{ es_group }}
    recurse=true

- name: setup elasticsearch config
  template:
    backup=yes
    src=elasticsearch.yml.j2
    dest={{ es_config_file_path }}
    owner={{ es_user }}
    group={{ es_group }}
  notify: restart elasticsearch
  tags:
    - config

- name: elasticsearch runit service
  include_tasks: runitconfig.yml
