- name: create runit directories for elasticsearch service
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
  with_items:
    - "/etc/sv/elasticsearch"
    - "/etc/sv/elasticsearch/log"

- name: install runit service for elasticsearch
  template:
    src: "elasticsearch.run.j2"
    dest: "/etc/sv/elasticsearch/run"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: 0755
  notify:
   - restart elasticsearch

- name: install runit log service for elasticsearch
  template:
    src: "elasticsearch.log.run.j2"
    dest: "/etc/sv/elasticsearch/log/run"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: 0755
  notify:
   - restart elasticsearch

- name: enable elasticsearch service
  become: yes
  runit:
    name: elasticsearch
    enabled: yes
    state: started
    service_dir: /etc/service
    service_src: /etc/sv
