---

filebeat_user_group: filebeat
filebeat_user: filebeat

filebeat_version: 5.6.3
filebeat_config_dir: "/opt/filebeat/conf.d"
filebeat_data_dir: "/opt/filebeat/data"
filebeat_logs_dir: "/opt/filebeat/logs"
filebeat_runit_log_dir: "/opt/filebeat/log"
filebeat_config_file_path: "/opt/filebeat/filebeat.yml"
filebeat_use_runit: true
# filebeat_elastic_search_hosts: [ "127.0.0.1:9200" ]
filebeat_logstash_hosts: [ "192.128.20.13:5044" ]
filebeat_logging_level: error
filebeat_output:
  file:
    filename: filebeat
    number_of_files: 7
    path: "/opt/filebeat/output"
    rotate_every_kb: 1_000
filebeat_prospectors:
  -
    type: log
    document_type: syslog
    paths:
      - /opt/logs/testlog.log
    ignore_older: 24h
    scan_frequency: 15s
