---

- set_fact: java_state="present"

- set_fact: java_state="latest"
  when: update_java == true

- name: RedHat - Ensure Java is installed
  become: yes
  yum: name={{ java }} state={{ java_state }}
  when: ansible_os_family == 'RedHat'
