---
- name: create metricbeat group
  group:
    name={{ metricbeat_group }}
    state=present

- name: create metricbeat user
  user:
    name={{ metricbeat_user }}
    group={{ metricbeat_group }}

- name: create metricbeat directories
  file:
    state=directory
    path={{ item }}
    owner={{ metricbeat_user }}
    group={{ metricbeat_group }}
    recurse=true
  with_items:
    - "{{ metricbeat_install_dir }}"
    - "{{ metricbeat_log_dir }}"
    - "{{ metricbeat_build_folder }}"

- name: download metricbeat archive
  get_url:
    url={{ metricbeat_url }}
    dest={{ metricbeat_build_folder }}/{{ metricbeat_archive }}
    force=no
  register: metricbeat_was_downloaded

- name: copy and unpack metricbeat archive
  unarchive:
    src={{ metricbeat_build_folder }}/{{ metricbeat_archive }}
    dest={{ metricbeat_install_dir }}
    copy=no

- name: link installed metricbeat directory to current
  file:
    state=link
    src={{ metricbeat_install_dir }}/{{ metricbeat_archive|replace('.tar.gz', '') }}
    path={{ metricbeat_install_dir }}/current
    owner={{ metricbeat_user }}
    group={{ metricbeat_group }}

- name: provide access permission to metricbeat directory
  file:
    state=directory
    path={{ metricbeat_install_dir }}/{{ metricbeat_archive|replace('.tar.gz', '') }}
    owner={{ metricbeat_user }}
    group={{ metricbeat_group }}
    recurse=true

- name: setup metricbeat config
  template:
    backup=yes
    src=metricbeat.yml.j2
    dest={{ metricbeat_config_file_path }}
    owner={{ metricbeat_user }}
    group={{ metricbeat_group }}
    mode=0644
  notify: restart linux metricbeat
  tags:
    - config

- name: metricbeat runit service
  include_tasks: runitconfig.yml
