---
- name: Ensure metricbeat is installed
  win_chocolatey:
    name: metricbeat
    version: "{{metricbeat_version}}"
    state: latest

- name: Ensure {{metricbeat_config_dir}} exists
  win_file: path={{metricbeat_config_dir}} state=directory

- name: Ensure main metricbeat.yml is generated
  win_template:
    src: metricbeat.yml.j2
    dest: "{{metricbeat_config_file_path}}"
  notify:
    - restart windows metricbeat

- name: Ensure metricbeat service is started
  win_service:
    name: metricbeat
    start_mode: auto
    state: started
