---
- name: restart kibana
  become: yes
  runit:
    name: "{{ kibana_service_name }}"
    enabled: yes
    state: restarted
    service_dir: /etc/service
    service_src: /etc/sv
  # notify:
  #  - restart runit
