---
# defaults file for elasticsearch

es_service_name: elasticsearch
es_archive: elasticsearch-6.6.0.tar.gz
es_url: https://artifacts.elastic.co/downloads/elasticsearch/{{ es_archive }}
es_user: elasticsearch
es_group: elasticsearch

es_java_install: true
es_install_dir: /opt/elasticsearch
es_build_folder: /tmp/elasticsearch
es_config_dir: /opt/elasticsearch/current/config
es_data_dir: /opt/elasticsearch/current/data
es_log_dir: /opt/elasticsearch/log
es_config: {}
es_config_file_path: /opt/elasticsearch/current/config/elasticsearch.yml

es_instancename: elasticnode
es_xpack_features: ["alerting","monitoring","graph","ml","security"]

es_host_address: "192.128.20.12"
es_host_port: "9200"

update_java: true
java: "{{ es_java | default('java-1.8.0-openjdk.x86_64') }}"
java_version: 1.8.0
